version: '3.8'
services:
  sanitizer:
    image: sanitizer
    build:
      context: .
    environment:
      TARGET_URL: "http://host.docker.internal:8080/server/oai/request"
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs  # Bind mount the "logs" folder on your laptop to "/app/logs" in the container
