version: '3.8'
services:
  sanitizer:
    image: sanitizer
    build:
      context: .
    environment:
      TARGET_URL: "http://islandora.io/oai/request"
    networks:
      shared_network:
        aliases:
          - islandora.io
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs  # Bind mount the "logs" folder on your laptop to "/app/logs" in the container
networks:
  shared_network:
    external: true
